#!/usr/bin/env bash
# redirect to another page
# Install Nginx web server if not already installed
apt-get update
apt-get install -y nginx

# Update the Nginx configuration using sed
sed -i '/server_name _;/a \tlocation \/redirect_me \{\t\treturn 301 https:\/\/www.youtube.com\/watch\?v=QH2-TGUlwu4;\}' /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
nginx -t

# Restart Nginx to apply the new configuration
systemctl restart nginx
