#!/usr/bin/env bash
# Install Nginx web server if not already installed

apt-get update
apt-get install -y nginx

# Create a custom 404 page with the required content
echo "Ceci n'est pas une page." > sudo tee /var/www/html/404.html

# Update the Nginx configuration to include the custom 404 page
sed -i '/listen \[::\]:80 default_server;/a \
\
    error_page 404 /404.html;\
    location = /404.html \{\
        internal;\
    \}' /etc/nginx/sites-available/default

# Test the Nginx configuration for syntax errors
nginx -t

# Restart Nginx to apply the new configuration
systemctl restart nginx
